### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by dejj** [schervontsev/PixivGifDownloader#1]
Receving the following error:

```
Exception in thread "main" java.lang.NullPointerException
    at pixivdownloader.PixivDownloader.downloadUrl(PixivDownloader.java:45)
    at pixivdownloader.PixivDownloader.main(PixivDownloader.java:98)
```

The line numbers don't correspond to anything in PixivDownloader.java; I'll try to rebuild the jar next.

**Comment by sergei-chervontsev** [comment]
I fixed it a year ago, but forgot to update binaries. Updated them now.
